### ISSUE TITLE
ie 11 compatibility ES2015

### ISSUE THREAD

**Issue by aymenet1** [gabrielferreiraa/react-redux-boilerplate#5]
when I use the app on ie 11 its not showing I got Script1002 error on ie11

**Comment by aymenet1** [comment]
to fix this issue I used    ` "query-string": "5.1.1" ` in package.json and 
```
 module.exports = {
  devtool: "source-map",
   entry: [
   "babel-polyfill", // Load this first
   "react-hot-loader/patch",
    "webpack-dev-server/client?",
    "webpack/hot/only-dev-server",
    common.entry.main
  ],
```
 in dev.config.json

**Comment by gabrielferreiraa** [comment]
Wow, nice! Thanks @aymenet1. But this repo is inactive!

**Comment by aymenet1** [comment]
I'm using your project for a year...
